View Jobs Applied
imran1289-ah/SOEN390-Team05-W23 pull request #131
Opened 2023-03-17 18:45 UTC by DasDeveloper

Added a summary of jobs applied for a user which is accessible from the navbar.
Added necessary css.
Added backend functionality.

2023-03-18 02:05 UTC, Aboudik1452 requested changes
Good work overall.
Please take a look at my comments, and let me know if you have questions!

2023-03-18 02:05 UTC, Aboudik1452 commented on src/client/src/css/viewJobsApplied.css
CSS is broken when resizing the window to a width higher than 640 pixels. You can see the horizontal scroll bar
![image](https://user-images.githubusercontent.com/78051064/226077480-6d34eeb0-6222-42d9-911d-0deb96438867.png)

2023-03-18 02:18 UTC, DasDeveloper commented on src/server/models/user.js
> +    jobsAppliedObject:[],
The difference is that one the first one contains only the id's of the jobs he has applied for while the second contains all the jobs he has applied for in JSON format. Changing the initial attribute to objects was too complicated and caused errors for other pages which is why i chose to add another one instead.

2023-03-18 02:18 UTC, DasDeveloper commented on src/server/routes/userRoutes.js
> +router.route("/:id/jobsObjectApplied").get(usersControllers.getUserJobsObjectApplied)
Yes, both are necessary. I imagine it will also be useful for future sprints.

2023-03-19 01:16 UTC, Aboudik1452 approved these changes

2023-03-19 16:13 UTC, Kunal22shah approved these changes
LGTM

2023-03-19 16:19 UTC, merged