Issue#33/upload resume cl
imran1289-ah/SOEN390-Team05-W23 pull request #72
Opened 2023-02-12 19:43 UTC by Kunal22shah

set up backend to allow a user to upload resume and cover letter to his User Profile.

2023-02-13 16:55 UTC, imran1289-ah approved these changes
This is good. But where does the cv and cover letter get saved (path where it gets saved)

2023-02-13 17:42 UTC, Kunal22shah commented
> I see your changes and its great !!. But where does the cv and cover letter get saved (path where it gets saved)? do they get added in the DB as files?
@imran1289-ah The files get saved in the server section under a new folder- uploads. I have also used the following format to better identify the files: user_id+filename.pdf

2023-02-14 01:34 UTC, Aboudik1452 requested changes
Good work on the upload resume feature!
Let me know if we should rename the file as mentioned in my comment!

2023-02-14 16:49 UTC, DasDeveloper approved these changes

2023-02-15 16:28 UTC, merged